#include "ciary.h"

int ensure_config_dir(void) {
    char *home = getenv("HOME");
    if (!home) return -1;
    
    char config_dir[MAX_PATH_SIZE];
    snprintf(config_dir, sizeof(config_dir), "%s/%s", home, CIARY_CONFIG_DIR);
    
    // Create directories recursively
    char *p = config_dir + strlen(home) + 1; // Skip home directory
    while ((p = strchr(p, '/')) != NULL) {
        *p = '\0';
        mkdir(config_dir, 0755);
        *p = '/';
        p++;
    }
    mkdir(config_dir, 0755);
    
    return 0;
}

char* get_config_path(char *path) {
    char *home = getenv("HOME");
    if (!home) return NULL;
    
    snprintf(path, MAX_PATH_SIZE, "%s/%s/%s", home, CIARY_CONFIG_DIR, CONFIG_FILE);
    return path;
}

char* get_default_journal_dir(char *path) {
    char *home = getenv("HOME");
    if (!home) return NULL;
    
    // First try: $HOME/Documents/journal
    char documents_dir[MAX_PATH_SIZE];
    snprintf(documents_dir, sizeof(documents_dir), "%s/Documents", home);
    
    struct stat st;
    if (stat(documents_dir, &st) == 0 && S_ISDIR(st.st_mode)) {
        snprintf(path, MAX_PATH_SIZE, "%s/Documents/journal", home);
    } else {
        // Fallback: $HOME/.local/share/ciary
        snprintf(path, MAX_PATH_SIZE, "%s/%s", home, CIARY_DATA_DIR);
    }
    
    return path;
}

void load_default_config(config_t *config) {
    // Get default username from environment
    char *user = getenv("USER");
    if (!user) user = getenv("USERNAME");
    if (!user) user = "friend";
    
    strncpy(config->preferred_name, user, MAX_NAME_SIZE - 1);
    config->preferred_name[MAX_NAME_SIZE - 1] = '\0';
    
    // Default journal directory
    if (!get_default_journal_dir(config->journal_directory)) {
        strcpy(config->journal_directory, "./journal"); // Ultimate fallback
    }
    
    // Default preferences
    strcpy(config->editor_preference, "auto"); // Auto-detect best editor
    strcpy(config->viewer_preference, "auto"); // Auto-detect best viewer
    config->show_ascii_art = 1;                // Enable ASCII art by default
    config->enable_personalization = 1;        // Enable personalization by default
}

int load_config(config_t *config) {
    char path[MAX_PATH_SIZE];
    if (!get_config_path(path)) return -1;
    
    FILE *file = fopen(path, "r");
    if (!file) {
        // Config doesn't exist, load defaults
        load_default_config(config);
        return 0;
    }
    
    // Load defaults first, then override with file values
    load_default_config(config);
    
    char line[MAX_LINE_SIZE];
    while (fgets(line, sizeof(line), file)) {
        // Skip comments and empty lines
        if (line[0] == '#' || line[0] == '\n' || line[0] == '\0') continue;
        
        // Remove trailing newline
        line[strcspn(line, "\n")] = '\0';
        
        // Parse key=value pairs
        char *equals = strchr(line, '=');
        if (!equals) continue;
        
        *equals = '\0';
        char *key = line;
        char *value = equals + 1;
        
        // Trim whitespace
        while (*key == ' ' || *key == '\t') key++;
        while (*value == ' ' || *value == '\t') value++;
        
        // Parse configuration values
        if (strcmp(key, "preferred_name") == 0) {
            strncpy(config->preferred_name, value, MAX_NAME_SIZE - 1);
            config->preferred_name[MAX_NAME_SIZE - 1] = '\0';
        }
        else if (strcmp(key, "journal_directory") == 0) {
            strncpy(config->journal_directory, value, MAX_PATH_SIZE - 1);
            config->journal_directory[MAX_PATH_SIZE - 1] = '\0';
        }
        else if (strcmp(key, "editor_preference") == 0) {
            strncpy(config->editor_preference, value, MAX_NAME_SIZE - 1);
            config->editor_preference[MAX_NAME_SIZE - 1] = '\0';
        }
        else if (strcmp(key, "viewer_preference") == 0) {
            strncpy(config->viewer_preference, value, MAX_NAME_SIZE - 1);
            config->viewer_preference[MAX_NAME_SIZE - 1] = '\0';
        }
        else if (strcmp(key, "show_ascii_art") == 0) {
            config->show_ascii_art = (strcmp(value, "true") == 0 || strcmp(value, "1") == 0);
        }
        else if (strcmp(key, "enable_personalization") == 0) {
            config->enable_personalization = (strcmp(value, "true") == 0 || strcmp(value, "1") == 0);
        }
    }
    
    fclose(file);
    return 0;
}

int save_config(const config_t *config) {
    if (ensure_config_dir() == -1) return -1;
    
    char path[MAX_PATH_SIZE];
    if (!get_config_path(path)) return -1;
    
    FILE *file = fopen(path, "w");
    if (!file) return -1;
    
    // Write configuration file with comments
    fprintf(file, "# Ciary Configuration File\n");
    fprintf(file, "# This file is automatically generated and can be edited manually\n\n");
    
    fprintf(file, "# Your preferred name (how Ciary addresses you)\n");
    fprintf(file, "preferred_name=%s\n\n", config->preferred_name);
    
    fprintf(file, "# Directory where journal entries are stored\n");
    fprintf(file, "journal_directory=%s\n\n", config->journal_directory);
    
    fprintf(file, "# Preferred text editor (auto, nvim, vim, nano, emacs, vi)\n");
    fprintf(file, "editor_preference=%s\n\n", config->editor_preference);
    
    fprintf(file, "# Preferred file viewer (auto, less, more, cat)\n");
    fprintf(file, "viewer_preference=%s\n\n", config->viewer_preference);
    
    fprintf(file, "# Show ASCII art on startup (true/false)\n");
    fprintf(file, "show_ascii_art=%s\n\n", config->show_ascii_art ? "true" : "false");
    
    fprintf(file, "# Enable personalized messages (true/false)\n");
    fprintf(file, "enable_personalization=%s\n", config->enable_personalization ? "true" : "false");
    
    fclose(file);
    return 0;
}

int setup_first_run(config_t *config) {
    char path[MAX_PATH_SIZE];
    if (!get_config_path(path)) return -1;
    
    // Check if config already exists
    struct stat st;
    if (stat(path, &st) == 0) {
        // Config exists, just load it
        return load_config(config);
    }
    
    // First run - setup configuration
    printf("🌟 Welcome to Ciary! 🌟\n\n");
    printf("It looks like this is your first time running Ciary.\n");
    printf("Let's set up a few preferences to make your experience more personal.\n\n");
    
    // Load defaults
    load_default_config(config);
    
    // Ask for preferred name
    printf("What would you like me to call you? (default: %s): ", config->preferred_name);
    fflush(stdout);
    
    char input[MAX_PATH_SIZE];
    if (fgets(input, sizeof(input), stdin)) {
        // Remove newline and use input if not empty
        input[strcspn(input, "\n")] = '\0';
        if (strlen(input) > 0) {
            strncpy(config->preferred_name, input, MAX_NAME_SIZE - 1);
            config->preferred_name[MAX_NAME_SIZE - 1] = '\0';
        }
    }
    
    // Ask for journal directory
    printf("\nWhere would you like to store your journal entries?\n");
    printf("(default: %s): ", config->journal_directory);
    fflush(stdout);
    
    if (fgets(input, sizeof(input), stdin)) {
        input[strcspn(input, "\n")] = '\0';
        if (strlen(input) > 0) {
            // Handle tilde expansion
            if (input[0] == '~' && input[1] == '/') {
                char *home = getenv("HOME");
                if (home) {
                    char expanded_path[MAX_PATH_SIZE];
                    snprintf(expanded_path, sizeof(expanded_path), "%s%s", home, input + 1);
                    strncpy(config->journal_directory, expanded_path, MAX_PATH_SIZE - 1);
                    config->journal_directory[MAX_PATH_SIZE - 1] = '\0';
                } else {
                    strncpy(config->journal_directory, input, MAX_PATH_SIZE - 1);
                    config->journal_directory[MAX_PATH_SIZE - 1] = '\0';
                }
            } else {
                strncpy(config->journal_directory, input, MAX_PATH_SIZE - 1);
                config->journal_directory[MAX_PATH_SIZE - 1] = '\0';
            }
        }
    }
    
    // Ask about personalization
    printf("\nWould you like personalized welcome messages? (Y/n): ");
    fflush(stdout);
    
    if (fgets(input, sizeof(input), stdin)) {
        input[strcspn(input, "\n")] = '\0';
        if (strlen(input) > 0 && (input[0] == 'n' || input[0] == 'N')) {
            config->enable_personalization = 0;
        }
    }
    
    // Ask about ASCII art
    printf("Show ASCII art on startup? (Y/n): ");
    fflush(stdout);
    
    if (fgets(input, sizeof(input), stdin)) {
        input[strcspn(input, "\n")] = '\0';
        if (strlen(input) > 0 && (input[0] == 'n' || input[0] == 'N')) {
            config->show_ascii_art = 0;
        }
    }
    
    // Save configuration
    if (save_config(config) == 0) {
        printf("\n✅ Configuration saved successfully!\n");
        printf("You can edit your preferences anytime in: %s\n\n", path);
        printf("Press Enter to continue...");
        getchar();
        return 0;
    } else {
        printf("\n❌ Warning: Could not save configuration file.\n");
        printf("Using default settings for this session.\n\n");
        printf("Press Enter to continue...");
        getchar();
        return -1;
    }
}